CREATE DATABASE DER_0_3;

USE DER_0_3;

CREATE TABLE MUNICIPIO(
	COD_MUNICIPIO INT,
	ID_MUNICIPIO INT, 
	NOMBRE_MUNICIPIO VARCHAR (100),
	PRIMARY KEY (COD_MUNICIPIO)
);

CREATE TABLE SECTOR(
	ID_SECTOR INT, 
	SECTOR VARCHAR (25),
	FAMILIA VARCHAR (50),
	AREA VARCHAR (50),
	ESPECIALIDAD VARCHAR (150),
	PRIMARY KEY (ID_SECTOR)
);

CREATE TABLE CENTRO(
	COD_CENTRO INT,
	ID_CENTRO INT,
    NOMBRE_CENTRO VARCHAR (150), 
    TELEFONO VARCHAR (12), 
    CORREO_ELECTRONICO VARCHAR (150),
    ID_CURSO VARCHAR (10), 
    DIRECCION_CENTRO VARCHAR (150),
    CODIGO_POSTAL INT,
    COD_MUNICIPIO INT,
    PRIMARY KEY (COD_CENTRO),
    FOREIGN KEY (COD_MUNICIPIO) REFERENCES MUNICIPIO (COD_MUNICIPIO)
);


CREATE TABLE CURSO(
	ID_CURSO VARCHAR (10),
	DESCRIPCION VARCHAR (150),
	DURACION_FORMACION INT, 
	DURACION_PRACTICAS INT, 
	ESPECIALIDAD_CERTIFICADO VARCHAR (3),
	MODALIDAD VARCHAR (15),
	ID_SECTOR INT,
    COD_CENTRO INT,
	PRIMARY KEY (ID_CURSO),
	FOREIGN KEY (ID_SECTOR) REFERENCES SECTOR (ID_SECTOR),
    FOREIGN KEY (COD_CENTRO) REFERENCES CENTRO (COD_CENTRO)
);


