CREATE DATABASE DER_0_4;

USE DER_0_4;

CREATE TABLE COD_MUNICIPIO (
	ID_MUNICIPIO INT auto_increment,
    PRIMARY KEY (ID_MUNICIPIO)
);

CREATE TABLE MUNICIPIO (
	ID_MUNICIPIO INT auto_increment, 
	NOMBRE_MUNICIPIO VARCHAR (100),
    FOREIGN KEY (ID_MUNICIPIO) REFERENCES COD_MUNICIPIO (ID_MUNICIPIO)
);

CREATE TABLE COD_SECTOR(
	ID_SECTOR INT,
    PRIMARY KEY (ID_SECTOR)
);

CREATE TABLE SECTOR(
	ID_SECTOR INT, 
	SECTOR VARCHAR (25),
	FAMILIA VARCHAR (50),
	AREA VARCHAR (50),
	ESPECIALIDAD VARCHAR (150),
	FOREIGN KEY (ID_SECTOR) REFERENCES COD_SECTOR (ID_SECTOR)
);

CREATE TABLE COD_CENTRO(
	ID_CENTRO INT, 
    PRIMARY KEY (ID_CENTRO)
);

CREATE TABLE CENTRO(
	ID_CENTRO INT,
    NOMBRE_CENTRO VARCHAR (150), 
    TELEFONO VARCHAR (12), 
    CORREO_ELECTRONICO VARCHAR (150),
    ID_CURSO VARCHAR (10), 
    DIRECCION_CENTRO VARCHAR (150),
    CODIGO_POSTAL INT,
    ID_MUNICIPIO INT,
    FOREIGN KEY (ID_CENTRO) REFERENCES COD_CENTRO (ID_CENTRO),
    FOREIGN KEY (ID_MUNICIPIO) REFERENCES COD_MUNICIPIO (ID_MUNICIPIO)
);

CREATE TABLE CURSO(
	ID_CURSO VARCHAR (10),
	DESCRIPCION VARCHAR (150),
	DURACION_FORMACION INT, 
	DURACION_PRACTICAS INT, 
	ESPECIALIDAD_CERTIFICADO VARCHAR (3),
	MODALIDAD VARCHAR (15),
	ID_SECTOR INT,
    ID_CENTRO INT,
	PRIMARY KEY (ID_CURSO),
	FOREIGN KEY (ID_SECTOR) REFERENCES COD_SECTOR (ID_SECTOR),
    FOREIGN KEY (ID_CENTRO) REFERENCES COD_CENTRO (ID_CENTRO)
);
