INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('', 'SISTEMAS Y TELEMATICA');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('1', 'Actividades auxiliares en la Industria alimentaria');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('10', 'Albanileria y acabados');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('11', 'Alimentos diversos');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('12', 'Alojamiento');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('13', 'Analisis y control');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('14', 'Asistencia social');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('15', 'Asistencia social y servicios al consumidor');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('16', 'Atencion sanitaria');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('17', 'Atencion social');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('18', 'Carnicas');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('19', 'Carpinteria y mueble');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('2', 'Actividades culturales y recreativas');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('20', 'Carroceria de vehiculos');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('21', 'Centros');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('22', 'Colocacion y montaje');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('23', 'Competencia clave');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('24', 'Compraventa');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('25', 'Comunicaciones');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('26', 'Conduccion de vehiculos por carretera');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('27', 'Confeccion en textil y piel');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('28', 'Conservas vegetales');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('29', 'Construcciones aeronauticas');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('3', 'Actividades fisico-deportivo recreativas');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('30', 'Construcciones metalicas');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('31', 'Desarrollo');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('32', 'Diseno grafico y multimedia');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('33', 'Edicion');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('34', 'Eficiencia energetica');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('35', 'Electromecanica de vehiculos');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('36', 'Energia electrica');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('37', 'Energias renovables');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('38', 'Equipos electronicos');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('39', 'Especialidades sin area definida (administracion y oficinas)');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('4', 'Actividades y tecnicas graficas artisticas');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('40', 'Especialidades sin area definida (agraria)');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('41', 'Estetica');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('42', 'Estructuras');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('43', 'Fabricacion electromecanica');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('44', 'Finanzas y seguros');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('45', 'Formacion y educacion');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('46', 'Frio y climatizacion');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('47', 'Ganaderia');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('48', 'Gas');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('49', 'Gestion ambiental');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('5', 'Administracion y auditoria');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('50', 'Gestion de la informacion y la comunicacion');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('51', 'Hormigon');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('52', 'Horticultura');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('53', 'Impresion');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('54', 'Informacion. promocion y desarrollo turistico');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('55', 'Informatica');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('56', 'Informatica complementaria');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('57', 'Instalaciones de telecomunicacion');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('58', 'Instalaciones electricas');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('59', 'Jardineria');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('6', 'Aeronautica');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('60', 'Joyeria y orfebreria');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('61', 'Laboratorio quimico');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('62', 'Lenguas y dialectos espanoles');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('63', 'Logistica comercial y gestion del transporte');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('64', 'Manipulacion alimentaria');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('65', 'Maquinaria');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('66', 'Maquinaria de Construccion');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('67', 'Maquinaria y equipo Industrial');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('68', 'Maquinas electromecanicas');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('69', 'Marketing y relaciones publicas');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('7', 'Agencias de viaje');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('70', 'Montaje y mantenimiento de instalaciones');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('71', 'Operaciones mecanicas');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('72', 'Orientacion laboral');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('73', 'Ornamentales y jardineria');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('74', 'Panaderia. pasteleria. confiteria y molineria');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('75', 'Peluqueria');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('76', 'Peluqueria y tratamientos de belleza');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('77', 'Peluqueria y tratamientos de piel y belleza');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('78', 'Pre-impresion');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('79', 'Prevencion y recuperacion');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('8', 'Agricultura');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('80', 'Produccion audiovisual');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('81', 'Produccion carpinteria y mueble');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('82', 'Produccion mecanica');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('83', 'Producciones fotograficas');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('84', 'Proyectos y seguimiento de Obras');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('85', 'Publicidad - imagen');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('86', 'Publicidad/imagen');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('87', 'Restauracion');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('88', 'Seguridad y prevencion');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('89', 'Seguridad y salud laboral');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('9', 'AgroTurismo');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('90', 'Seguros');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('91', 'Servicios al consumidor');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('92', 'Servicios y productos sanitarios');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('93', 'Sistemas y telematica');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('94', 'Soporte y ayuda al diagnostico');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('95', 'Transformacion y conversion en industrias graficas');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('96', 'Transporte por carretera');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('97', 'Turismo');
INSERT INTO prsi_8_2.AREA (ID_AREA, AREA) VALUES ('98', 'Venta');
